language: node_js
node_js: "7"
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g serverless

script:
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

deploy:
  - provider: script
    script: serverless deploy --stage production
    on:
      branch: master
  - provider: script
    script: serverless deploy --stage dev
    on:
      branch: develop
